name: "Build"
on:
  push:
    branches:
      - 'feature/**'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 16
        uses: actions/setup-java@v3
        with:
          java-version: '16'
          distribution: 'zulu'
          cache: 'gradle'
      - name: Build
        run: ./gradlew build